routes/web.php
<?php

use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PelanggaranController;
use App\Http\Controllers\Admin\SiswaController as AdminSiswaController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SanksiController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/login');
});


Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/lupa-katasandi', [HomeController::class, 'reset'])->name('reset-password');
Route::post('/lupa-katasandi', [HomeController::class, 'resetPost'])->name('reset-password.store');
Route::group(['prefix' => 'admin', 'middleware' => ['cekadmin','auth'] ], function()
{
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-admin');
    Route::get('/reset-password/{id}', [AdminController::class, 'resetPassword'])->name('reset-password-admin.store');
    Route::get('/pelanggaran', [PelanggaranController::class, 'index'])->name('pelanggaran-admin');
    Route::get('/add-pelanggaran', [PelanggaranController::class, 'add'])->name('add-pelanggaran-admin');
    Route::post('/add-pelanggaran', [PelanggaranController::class, 'post'])->name('post-pelanggaran-admin');
    Route::get('/delete-pelanggaran/{id}', [PelanggaranController::class, 'delete'])->name('delete-pelanggaran-admin');
    Route::get('/edit-pelanggaran/{id}', [PelanggaranController::class, 'edit'])->name('edit-pelanggaran-admin');
    Route::post('/put-pelanggaran/{id}', [PelanggaranController::class, 'put'])->name('put-pelanggaran-admin');

    Route::resource('siswa-admin', AdminSiswaController::class);
    Route::resource('sanksi-admin', SanksiController::class);
    Route::resource('user-admin', UserController::class);

    Route::get('/tambah-pelanggaran/{id}', [AdminController::class, 'tambahPelanggaran'])->name('add-pelanggaran-siswa');
    Route::post('/tambah-pelanggaran-siswa/{id}', [AdminController::class, 'tambahPelanggaranSiswa'])->name('tambah-pelanggaran-siswa');
    Route::get('/delete-pelanggaran/{id}/{user_id}', [AdminController::class, 'deletePelanggaranSiswa'])->name('delete-pelanggaran-siswa');

    Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan-admin');
});
Route::get('/cetak', [LaporanController::class, 'cetak'])->name('cetak-all-admin');
Route::get('/cetak-pelanggaran/siswa/{id}', [LaporanController::class, 'cetakPelanggaranSiswa'])->name('cetak-pelanggaran-siswa-admin');
Route::resource('profile-admin',ProfileController::class);

Route::group(['prefix' => 'siswa', 'middleware' => ['ceksiswa','auth'] ], function()
{
  Route::get('/dashboard', [SiswaController::class, 'index'])->name('dashboard-siswa');
  Route::post('/send-message', [SiswaController::class, 'sendMessage'])->name('send-message-siswa');
});

Route::group(['prefix' => 'guru', 'middleware' => ['cekguru','auth'] ], function()
{
  Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-guru');
});

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'kelas',
        'jurusan_id',
        'jumlah_point'
    ];

    public function user()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
 
}

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;


class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $auth = Auth::user();
        return view('page.admin.profile.index', compact('auth'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string',
            'nis' => 'required|numeric',
            'email' => 'required|email'
        ]);
        $auth = Auth::user();
        $cek = User::where('nis',$request->nis)->first();
        if(isset($cek)){
            if($cek->id != $auth->id){
                return redirect()->route('profile-admin.index')->with('error','NIK Sudah terdaftar');
            }
        }

        $cek = User::where('email',$request->email)->first();
        if(isset($cek)){
            if($cek->id != $auth->id){
                return redirect()->route('profile-admin.index')->with('error','Email Sudah terdaftar');
            }
        }
        // dd($auth->nis);
       
        // $data = $request->all();
        $user = User::find($auth->id);
        $user->name=$request->name;
        $user->nis=$request->nis;
        $user->email=$request->email;
        $user->save();
        return redirect()->route('profile-admin.index')->with('success','Profil berhasil diupdate');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $auth = Auth::user();
        return view('page.admin.profile.changepassword', compact('auth'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        Validator::extend('password', function ($attribute, $value, $parameters, $validator) {
            return Hash::check($value, Auth::user()->password);
        });

        // message for custom validation
        $messages = [
            'password' => 'Invalid current password.',
        ];

        // validate form
        $validator = Validator::make(request()->all(), [
            'current_password'      => 'required|password',
            'password'              => 'required|min:6|confirmed',
            'password_confirmation' => 'required',

        ], $messages);

        // if validation fails
        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator->errors());
        }

        // update password
        $user = User::find(Auth::id());

        $user->password = bcrypt(request('password'));
        $user->save();
        return redirect()->route('profile-admin.index')->with('success','Password berhasil diganti');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/page/admin/profile/changepassword.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-success">
                    <h3 class="card-title">Ganti Password {{$auth->name}}</h3>
                  </div>
                  <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <form method="POST" action="{{route('profile-admin.update',$auth->id)}}">
                        @method('PUT')
                        @csrf
                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group ">
                            <label class="">Password Sekarang</label>
                            <input type="password" name="current_password" class="form-control" required>
                          </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group ">
                              <label class="">Password Baru</label>
                              <input type="password" name="password" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group ">
                              <label class="">Konfirmasi Password</label>
                              <input type="password" name="password_confirmation" class="form-control" required>
                            </div>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-primary pull-right">Ganti Password</button>
                      <div class="clearfix"></div>
                    </form>
                  </div>
                </div>
              </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/profile/index.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-info">
                    <h3 class="card-title">Edit Profile {{$auth->name}}</h3>
                  </div>
                  <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <form method="POST" action="{{route('profile-admin.store')}}">
                        @csrf
                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group ">
                            <label class="">Nama</label>
                            <input type="text" name="name" class="form-control" value="{{$auth->name}}" required>
                          </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group ">
                              <label class="">NIK</label>
                              <input type="text" name="nis" class="form-control" required value="{{$auth->nis}}">
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group ">
                              <label class="">Email</label>
                              <input type="text" name="email" class="form-control" required value="{{$auth->email}}">
                            </div>
                          </div>
                      </div>
                      <a href="{{route('profile-admin.show',$auth->id)}}" class="btn btn-warning pull-right">Ganti Password</a>
                      <button type="submit" class="btn btn-primary pull-right">Update</button>
                      <div class="clearfix"></div>
                    </form>
                  </div>
                </div>
              </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection