routes/web.php
<?php

use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PelanggaranController;
use App\Http\Controllers\Admin\SiswaController as AdminSiswaController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SanksiController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/login');
});


Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/lupa-katasandi', [HomeController::class, 'reset'])->name('reset-password');
Route::post('/lupa-katasandi', [HomeController::class, 'resetPost'])->name('reset-password.store');
Route::group(['prefix' => 'admin', 'middleware' => ['cekadmin','auth'] ], function()
{
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-admin');
    Route::get('/reset-password/{id}', [AdminController::class, 'resetPassword'])->name('reset-password-admin.store');
    Route::get('/pelanggaran', [PelanggaranController::class, 'index'])->name('pelanggaran-admin');
    Route::get('/add-pelanggaran', [PelanggaranController::class, 'add'])->name('add-pelanggaran-admin');
    Route::post('/add-pelanggaran', [PelanggaranController::class, 'post'])->name('post-pelanggaran-admin');
    Route::get('/delete-pelanggaran/{id}', [PelanggaranController::class, 'delete'])->name('delete-pelanggaran-admin');
    Route::get('/edit-pelanggaran/{id}', [PelanggaranController::class, 'edit'])->name('edit-pelanggaran-admin');
    Route::post('/put-pelanggaran/{id}', [PelanggaranController::class, 'put'])->name('put-pelanggaran-admin');

    Route::resource('siswa-admin', AdminSiswaController::class);
    Route::resource('sanksi-admin', SanksiController::class);
    Route::resource('user-admin', UserController::class);

    Route::get('/tambah-pelanggaran/{id}', [AdminController::class, 'tambahPelanggaran'])->name('add-pelanggaran-siswa');
    Route::post('/tambah-pelanggaran-siswa/{id}', [AdminController::class, 'tambahPelanggaranSiswa'])->name('tambah-pelanggaran-siswa');
    Route::get('/delete-pelanggaran/{id}/{user_id}', [AdminController::class, 'deletePelanggaranSiswa'])->name('delete-pelanggaran-siswa');

    Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan-admin');
});
Route::get('/cetak', [LaporanController::class, 'cetak'])->name('cetak-all-admin');
Route::get('/cetak-pelanggaran/siswa/{id}', [LaporanController::class, 'cetakPelanggaranSiswa'])->name('cetak-pelanggaran-siswa-admin');
Route::resource('profile-admin',ProfileController::class);

Route::group(['prefix' => 'siswa', 'middleware' => ['ceksiswa','auth'] ], function()
{
  Route::get('/dashboard', [SiswaController::class, 'index'])->name('dashboard-siswa');
  Route::post('/send-message', [SiswaController::class, 'sendMessage'])->name('send-message-siswa');
});

Route::group(['prefix' => 'guru', 'middleware' => ['cekguru','auth'] ], function()
{
  Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-guru');
});

app/Http/Controllers/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PelanggaranSiswa;
use App\Models\Profile;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswa = User::where('level','siswa')->get();
        // dd($siswa);
        return view("page.admin.siswa.index", compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
        return view("page.admin.siswa.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nis' => 'required|unique:users,nis',
            'name' => 'required|string',
            'email' => 'required|email|unique:users,email',
            'kelas' => 'required|string',
            'jurusan'=>'required',
            'tempat_lahir'=>'required',
            'orang_tua'=>'required',
            'tanggal_lahir'=>'required',

        ]);
        $user = new User();
        $user->name=$request->name;
        $user->nis=$request->nis;
        $user->email=$request->email;
        $user->jenis_kelamin=$request->jenis_kelamin;
        $user->password=Hash::make('smk_bisa');
        $user->level = "siswa";
        $user->save();
        $profil = new Profile();
        $profil->user_id=$user->id;
        $profil->kelas=$request->kelas;
        $profil->jurusan=$request->jurusan;
        $profil->tanggal_lahir=$request->tanggal_lahir;
        $profil->tempat_lahir=$request->tempat_lahir;
        $profil->orang_tua=$request->orang_tua;
        $profil->save();
        return redirect()->route('siswa-admin.index')->with('success','Siswa berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {  
        $siswa = User::find($id);
        $pelanggaran = PelanggaranSiswa::where('user_id',$id)->get();
        return view('page.admin.siswa.show', compact('pelanggaran','siswa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = User::find($id);
        return view("page.admin.siswa.edit", compact('siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'nis' => 'required',
            'name' => 'required|string',
            'email' => 'required|email',
            'kelas' => 'required|string',
            'jurusan'=>'required',
            'tempat_lahir'=>'required',
            'orang_tua'=>'required',
            'tanggal_lahir'=>'required',
        ]);
        $cek = User::where('nis',$request->nis)->first();

        if(isset($cek)){
            if($cek->id != $id){
                return redirect()->route('siswa-admin.edit',$id)->with('error','NIS Sudah terdaftar');
            }
        }

        $cek = User::where('email',$request->email)->first();

        if(isset($cek)){
            if($cek->id != $id){
                return redirect()->route('siswa-admin.edit',$id)->with('error','Email Sudah terdaftar');
            }
        }


        $user= User::find($id);
        $user->name=$request->name;
        $user->email=$request->email;
        $user->nis=$request->nis;
        $user->jenis_kelamin=$request->jenis_kelamin;
        $user->save();

        $profil = Profile::where('user_id',$id)->first();
        $profil->kelas=$request->kelas;
        $profil->jurusan=$request->jurusan;
        $profil->tanggal_lahir=$request->tanggal_lahir;
        $profil->tempat_lahir=$request->tempat_lahir;
        $profil->orang_tua=$request->orang_tua;
        $profil->save();
        return redirect()->route('siswa-admin.index')->with('success','Siswa berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::find($id);
        $profile=Profile::where('user_id',$id)->first();
        $profile->delete();
        $user->delete();
        return redirect()->route('siswa-admin.index')->with('success','Siswa berhasil dihapus');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\MasterPelanggaran;
use App\Models\PelanggaranSiswa;
use App\Models\Profile;
use App\Models\User;
use Bantuan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class SiswaController extends Controller
{
    public function index()
    {
        $pelanggaran = Profile::orderBy('jumlah_point','desc')->limit(10)->get();
        $pelanggaranuser = PelanggaranSiswa::where('user_id',Auth::user()->id)->orderBy('waktu_pelanggaran','desc')->get();
        $admin = User::where('level','!=','siswa')->get();
        // dd($admin);
        return view('page.siswa.index', compact('pelanggaran','pelanggaranuser','admin'));
    }
    public function sendMessage(Request $request)
    {
        
        $pesan = str_replace(" ","%20",$request->message);
        $admin = User::find($request->admin);
        // dd($admin);
        if(!isset($admin->no_hp)){
            return redirect()->route('dashboard-siswa')->with('error',"Nomer HP $admin->name tidak valid mohon pilih admin lain");
        }
        $nohp = Bantuan::changeNoHP($admin->no_hp);
        $url = "https://api.whatsapp.com/send?phone=$nohp&text=$pesan&source=&data=";
        return Redirect::to($url);


        // dd($test);
        // 
    }
}

resources/views/page/admin/siswa/create.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-success">
                        <h3 class="card-title">Tambah Siswa</h3>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <form method="POST" action="{{route('siswa-admin.store')}}">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Nama</label>
                                        <input type="text" name="name" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">NIS</label>
                                        <input type="number" name="nis" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Email</label>
                                        <input type="email" name="email" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Jurusan</label>
                                        <input type="text" name="jurusan" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Tempat Lahir</label>
                                        <input type="text" name="tempat_lahir" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Tanggal lahir</label>
                                        <input type="date" name="tanggal_lahir" class="form-control" required placeholder="dd/mm/yyyy">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Nama Orang Tua</label>
                                        <input type="text" name="orang_tua" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label for="jk">Jenis Kelamin</label>
                                        <select class="form-control" name="jenis_kelamin" id="jk">
                                            <option value="laki-laki">Laki-laki</option>
                                            <option value="perempuan">Perempuan</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label for="selectkelas">Kelas</label>
                                        <select class="form-control" name="kelas" id="selectkelas">
                                            <option value="X">X</option>
                                            <option value="XI">XI</option>
                                            <option value="XII">XII</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <p>Password Default dari siswa adalah <b>smk_bisa</b> </p>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary pull-right">Tambah</button>
                                <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/siswa/edit.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-success">
                        <h3 class="card-title">Edit Siswa {{$siswa->name}}</h3>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <form method="POST" action="{{route('siswa-admin.update',$siswa->id)}}">
                            @method("PUT")
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Nama</label>
                                        <input type="text" name="name" class="form-control" required value="{{$siswa->name}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">NIS</label>
                                        <input type="number" name="nis" class="form-control" required value="{{$siswa->nis}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Email</label>
                                        <input type="email" name="email" class="form-control" required value="{{$siswa->email}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Jurusan</label>
                                        <input type="text" name="jurusan" class="form-control" required value="{{$siswa->profile->jurusan}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Tempat Lahir</label>
                                        <input type="text" name="tempat_lahir" class="form-control" required value="{{$siswa->profile->tempat_lahir}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Tanggal lahir</label>
                                        <input type="date" name="tanggal_lahir" class="form-control" required value="{{$siswa->profile->tanggal_lahir}}" placeholder="dd/mm/yyyy">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Nama Orang Tua</label>
                                        <input type="text" name="orang_tua" class="form-control" required value="{{$siswa->profile->orang_tua}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label for="jk">Jenis Kelamin</label>
                                        <select class="form-control" name="jenis_kelamin" id="jk">
                                            <option value="laki-laki" {{$siswa->jenis_kelamin == "laki-laki"  ? 'selected' : ''}} >Laki-laki</option>
                                            <option value="perempuan" {{$siswa->jenis_kelamin == "perempuan"  ? 'selected' : ''}}>Perempuan</option>
                                            
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label for="selectkelas">Kelas</label>
                                        <select class="form-control" name="kelas" id="selectkelas">
                                            <option value="X" {{$siswa->profile->kelas == "X"  ? 'selected' : ''}} >X</option>
                                            <option value="XI" {{$siswa->profile->kelas == "XI"  ? 'selected' : ''}} >XI</option>
                                            <option value="XII" {{$siswa->profile->kelas == "XII"  ? 'selected' : ''}} >XII</option>
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary pull-right">Update</button>
                                <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/siswa/index.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h3 class="card-title">Data Siswa</h3>
                    </div>
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('delete'))
                    <div class="alert alert-danger  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <div class="card-body table-responsive">
                        <a href="{{route('siswa-admin.create')}}" class="btn btn-success">Tambah Siswa</a>
                        <table class="table table-hover table-bordered tableDatatables mt-3">
                            <thead class="text-warning">
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>NIS</th>
                                    <th>Email</th>
                                    <th>Kelas</th>
                                    <th>Jurusan</th>
                                    <th>Point</th>
                                    <th>Tempat, Tanggal Lahir</th>
                                    <th>Nama Orang Tua</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($siswa as $s)
                                
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$s->name}}</td>
                                    <td>{{$s->nis}}</td>
                                    <td>{{$s->email}}</td>
                                    <td>{{$s->profile->kelas}}</td>
                                    <td>{{$s->profile->jurusan}}</td>
                                    <td>{{$s->profile->jumlah_point}}</td>
                                    <td>{{$s->profile->tempat_lahir}} , {{$s->profile->tanggal_lahir}}</td>
                                    <td>{{$s->profile->orang_tua}}</td>
                                    <td>
                                        <div class="d-flex flex-row">
                                            <a href="{{route('siswa-admin.show',$s->id)}}" class="btn btn-info">Point Pelanggaran</a>
                                            <a href="{{route('siswa-admin.edit',$s->id)}}"
                                                class="btn btn-warning">Edit</a>
                                            <form action="{{route('siswa-admin.destroy',$s->id)}}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-danger">
                                                    Hapus
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/siswa/show.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h3 class="card-title">Data Pelanggaran Siswa <b>{{$siswa->name}}</b> </h3>
                    </div>
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('delete'))
                    <div class="alert alert-danger  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <div class="card-body table-responsive">
                        <a href="{{route('add-pelanggaran-siswa',$siswa->id)}}" class="btn btn-success">+ Pelanggaran</a>
                        <table class="table table-hover table-bordered tableDatatables mt-3">
                            <thead class="text-warning">
                                <tr>
                                    <th>No</th>
                                    <th>Waktu Pelanggaran</th>
                                    <th>Pelanggaran</th>
                                    <th>Point</th>
                                    <th>Sanksi</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($pelanggaran as $p)
                                
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$p->waktu_pelanggaran}}</td>
                                    <td>{{$p->MasterPelanggaran->bentuk_pelanggaran}}</td>
                                    <td>{{$p->MasterPelanggaran->point}}</td>
                                    <td>
                                        {{Bantuan::getSanksi($p->MasterPelanggaran->point)}}
                                    </td>
                                    
                                    <td>
                                        <div class="d-flex flex-row">
                                            <a href="{{route('delete-pelanggaran-siswa',[$p->id,$siswa->id])}}"
                                                    class="btn btn-danger">Delete</a>
                                          
                                        </div>
                                    </td>
                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection