routes/web.php
<?php

use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PelanggaranController;
use App\Http\Controllers\Admin\SiswaController as AdminSiswaController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SanksiController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/login');
});


Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/lupa-katasandi', [HomeController::class, 'reset'])->name('reset-password');
Route::post('/lupa-katasandi', [HomeController::class, 'resetPost'])->name('reset-password.store');
Route::group(['prefix' => 'admin', 'middleware' => ['cekadmin','auth'] ], function()
{
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-admin');
    Route::get('/reset-password/{id}', [AdminController::class, 'resetPassword'])->name('reset-password-admin.store');
    Route::get('/pelanggaran', [PelanggaranController::class, 'index'])->name('pelanggaran-admin');
    Route::get('/add-pelanggaran', [PelanggaranController::class, 'add'])->name('add-pelanggaran-admin');
    Route::post('/add-pelanggaran', [PelanggaranController::class, 'post'])->name('post-pelanggaran-admin');
    Route::get('/delete-pelanggaran/{id}', [PelanggaranController::class, 'delete'])->name('delete-pelanggaran-admin');
    Route::get('/edit-pelanggaran/{id}', [PelanggaranController::class, 'edit'])->name('edit-pelanggaran-admin');
    Route::post('/put-pelanggaran/{id}', [PelanggaranController::class, 'put'])->name('put-pelanggaran-admin');

    Route::resource('siswa-admin', AdminSiswaController::class);
    Route::resource('sanksi-admin', SanksiController::class);
    Route::resource('user-admin', UserController::class);

    Route::get('/tambah-pelanggaran/{id}', [AdminController::class, 'tambahPelanggaran'])->name('add-pelanggaran-siswa');
    Route::post('/tambah-pelanggaran-siswa/{id}', [AdminController::class, 'tambahPelanggaranSiswa'])->name('tambah-pelanggaran-siswa');
    Route::get('/delete-pelanggaran/{id}/{user_id}', [AdminController::class, 'deletePelanggaranSiswa'])->name('delete-pelanggaran-siswa');

    Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan-admin');
});
Route::get('/cetak', [LaporanController::class, 'cetak'])->name('cetak-all-admin');
Route::get('/cetak-pelanggaran/siswa/{id}', [LaporanController::class, 'cetakPelanggaranSiswa'])->name('cetak-pelanggaran-siswa-admin');
Route::resource('profile-admin',ProfileController::class);

Route::group(['prefix' => 'siswa', 'middleware' => ['ceksiswa','auth'] ], function()
{
  Route::get('/dashboard', [SiswaController::class, 'index'])->name('dashboard-siswa');
  Route::post('/send-message', [SiswaController::class, 'sendMessage'])->name('send-message-siswa');
});

Route::group(['prefix' => 'guru', 'middleware' => ['cekguru','auth'] ], function()
{
  Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard-guru');
});

app/Models/Sanksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sanksi extends Model
{
    use HasFactory;
    protected $table = 'sanksi';
    protected $fillable = [
        'kode_sanksi',
        'sanksi',
        'point_min',
        'point_max'
    ];
}

app/Http/Controllers/Admin/SanksiController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Sanksi;
use Illuminate\Http\Request;

class SanksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sanksi = Sanksi::all();
        return view('page.admin.sanksi.index', compact('sanksi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.admin.sanksi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'kode_sanksi' => 'required|string',
            'sanksi' => 'required|string',
            'point_min'=>'required|numeric',
            'point_max'=>'required|numeric',
        ]);
        $data = $request->all();
        Sanksi::create($data);
        return redirect()->route('sanksi-admin.index')->with('success','Sanksi Berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sanksi=Sanksi::find($id);
        return view('page.admin.sanksi.edit', compact('sanksi'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'kode_sanksi' => 'required|string',
            'sanksi' => 'required|string',
            'point_min'=>'required|numeric',
            'point_max'=>'required|numeric',
        ]);
        $data = $request->all();
        $sanksi= Sanksi::find($id);
        $sanksi->update($data);
        return redirect()->route('sanksi-admin.index')->with('success','Sanksi Berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sanksi = Sanksi::find($id);
        $sanksi->delete();
        return redirect()->route('sanksi-admin.index')->with('success','Sanksi Berhasil dihapus');
    }
}

resources/views/page/admin/sanksi/create.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-success">
                        <h3 class="card-title">Tambah Sanksi</h3>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <form method="POST" action="{{route('sanksi-admin.store')}}">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Kode Sanksi</label>
                                        <input type="text" name="kode_sanksi" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Sanksi</label>
                                        <input type="text" name="sanksi" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Point Minimal</label>
                                        <input type="number" name="point_min" class="form-control" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Point Maksimal</label>
                                        <input type="number" name="point_max" class="form-control" required>
                                    </div>
                                </div>
                               
                                <button type="submit" class="btn btn-primary pull-right">Tambah</button>
                                <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/sanksi/edit.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-success">
                        <h3 class="card-title">Edit Sanksi {{$sanksi->kode_sanksi}}</h3>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                        <form method="POST" action="{{route('sanksi-admin.update',$sanksi->id)}}">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Kode Sanksi</label>
                                        <input type="text" name="kode_sanksi" class="form-control" required value="{{$sanksi->kode_sanksi}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Sanksi</label>
                                        <input type="text" name="sanksi" class="form-control" required value="{{$sanksi->sanksi}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Point Minimal</label>
                                        <input type="number" name="point_min" class="form-control" required value="{{$sanksi->point_min}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label class="">Point Maksimal</label>
                                        <input type="number" name="point_max" class="form-control" required value="{{$sanksi->point_max}}">
                                    </div>
                                </div>
                               
                                <button type="submit" class="btn btn-primary pull-right">Update</button>
                                <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection

resources/views/page/admin/sanksi/index.blade.php
@extends('layouts.adminpage')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h3 class="card-title">Data Sanksi</h3>
                    </div>
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    @if ($message = Session::get('delete'))
                    <div class="alert alert-danger  ">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <div class="card-body table-responsive">
                        @if (Auth::user()->level=='guru')
                        <a href="{{route('sanksi-admin.create')}}" class="btn btn-success">+ Sanksi</a>
                        @endif
                        <table class="table table-hover table-bordered tableDatatables mt-3">
                            <thead class="text-warning">
                                <tr>
                                    <th>No</th>
                                    <th>Kode Sanksi</th>
                                    <th>Sanksi</th>
                                    <th>Poin</th>
                                    @if (Auth::user()->level=='guru')
                                    <th>Aksi</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($sanksi as $s)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$s->kode_sanksi}}</td>
                                    <td>{{$s->sanksi}}</td>
                                    <td>{{$s->point_min}} - {{$s->point_max}}</td>
                                    @if (Auth::user()->level=='guru')
                                    <td>
                                        <div class="d-flex flex-row">
                                            <a href="{{route('sanksi-admin.edit',$s->id)}}"
                                                class="btn btn-warning">Edit</a>
                                            <form action="{{route('sanksi-admin.destroy',$s->id)}}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-danger">
                                                    Hapus
                                                </button>
                                            </form>
                                        </div>
                                    </td>  
                                    @endif
                                    
                                </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@push('addon-script')

@endpush

@endsection